title: <p align="center"> Mohammed Rahamathulla </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="TBD">Resume</a> |
  <a href="https://www.linkedin.com/in/mohammed-rahamathulla-4008209a/">LinkedIn</a> |
  <a href="https://github.com/md-rahmat">GitHub</a>
  
  <br>
  An accomplished and global clinical systems operation professional with a proven ability
  to facilitate corporate success through effective leadership of initiatives, programs, 
  projects, and teams.
  <br>
  
  </p>



theme: jekyll-theme-minimal
