title: <p align="left">Mohammed Rahamathulla</p>
logo: /assets/img/logo.png

description:
  <p align="left">
  <a href="TBD">Resume</a> |
  <a href="https://www.linkedin.com/in/mohammed-rahamathulla-4008209a/">LinkedIn</a> |
  <a href="https://github.com/md-rahmat">GitHub</a>
  
  <br>
       An IT-Healthcare enthusiast focused on integration of Human Data Science and cutting-edge technologies to <br>
       develop innovative, efficient and effective solutions that drive healthcare – and human health – forward.<br>
       Helping to accelerate drug development, shorten the journey of a molecule to market and bring patients closer<br>
       to affordable healthcare.
  <br>
  
  </p>



theme: jekyll-theme-minimal
