# title: <p align="center"> Mohammed Rahamathulla </p>
logo: /assets/img/logo.png

description:
  title: <p align="center"> Mohammed Rahamathulla </p>
  <p align="left">
  <a href="TBD">Resume</a> |
  <a href="https://www.linkedin.com/in/mohammed-rahamathulla-4008209a/">LinkedIn</a> |
  <a href="https://github.com/md-rahmat">GitHub</a>
  
  <br>
       An IT-Healthcare enthusiast focused on a role to explore Human Data Science and cutting-edge technologies to <br>
       develop innovative, efficient and effective solutions that drive healthcare – and human health – forward.<br>
       Extremely fortunate to pursue my passion through profession and contribute to global clinical community vision <br>
       that aims to accelerate drug development, shorten the journey of a molecule to market and bring patients closer<br>
       to affordable healthcare because they deserve another chance.
  <br>
  
  </p>



theme: jekyll-theme-minimal
