title: <p align="center"> Mohammed Rahamathulla </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="TBD">Resume</a> |
  <a href="https://www.linkedin.com/in/mohammed-rahamathulla-4008209a/">LinkedIn</a> |
  <a href="https://github.com/md-rahmat">GitHub</a>
  
  <br>
  An accomplished and global clinical systems operation professional with a proven ability to facilitate corporate success through effective leadership <br>
  of initiatives, programs,projects, and teams.An agile learner with a history of delivering innovative solutions to improve the process and deliver <br>
  projects on time. Adept at managing global, multi-site teams, migrating data services, and coordinating application development, testing, and deployments.
  
  Excellent analytical and forecasting skills, experienced in deploying advanced healthcare solutions in critical and patient safety applications <br>
  of global scope, namely large-scale worldwide clinical drug trials. 12.8+ years combined experience in varying positions within data management and <br>
  operations oversight in the pharmaceutical industry.Recognized for poised liaison and point-of-contact for operations and delivery with major clients <br>
  including resource management, projections, developing metrics & KPI’s and the creation of unique processes customized to client needs.<br>
  Significant problem-solving skills assist in approaching and solving challenging operating issues. Significant cross-functional training experience <br>
  allows for a more informed and uniform knowledge base across multiple levels of organizations.A collegial and accessible management style fosters stronger <br>
  employee/team engagement and improved morale.
  <br>
  
  </p>



theme: jekyll-theme-minimal
